config/routes.rb
PLPredictions::Application.routes.draw do
  devise_for :users

  get "points" => "points#index"

  get "/leaderboard" => "leaderboards#index"

  get "/results" => "results#index"

  resources :predictions
  get "/my_predictions" => "predictions#my_predictions"
  
  resources :fixtures

  root :to => 'leaderboards#index'


end

app/models/fixture.rb
class Fixture < ActiveRecord::Base
  attr_accessible :team_a_name, :team_b_name, :match_date 
end

app/models/prediction.rb
class Prediction < ActiveRecord::Base
  belongs_to :user
  attr_accessible :team_a_name, :team_b_name, :team_a_score, :team_b_score, :match_date 
end

app/models/result.rb
class Result < ActiveRecord::Base
  attr_accessible :team_a_name, :team_b_name, :team_a_score, :team_b_score, :match_date
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :predictions

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  accepts_nested_attributes_for :predictions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fixtures_controller.rb
class FixturesController < ApplicationController
  
  def index
    @fixtures = Fixture.all
  end

  def new
    @fixture = Fixture.new
  end

  def create 
    @fixture = Fixture.new(params[:fixture])
    if @fixture.save
      redirect_to root_path
    else
      render :new
    end
  end
  
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  
  def index
  end
  
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController


  def index
  end

end

app/controllers/points_controller.rb
class PointsController < ApplicationController


  def index
  end

end

app/controllers/points_scoring_controller.rb
myclassinstance = MyNewClass.new
myclassinstance.mymethod(@user.predictions)

app/controllers/predictions_controller.rb
class PredictionsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @predictions = Prediction.all
  end

  def my_predictions
     @predictions = current_user.predictions
  end

  def new
    @prediction = Prediction.new
    @fixtures = Fixture.all
  end

  #bit of hackaroo here...needs refactoring for failed saves
  def create
    params[:predictions].each do |prediction|
      @prediction = current_user.predictions.new(prediction)
      if @prediction.valid?
         @prediction.save
      end
    end
    redirect_to root_path
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_login
    if !current_user
      link_to "Log In", new_user_session_path
    else 
      link_to "Logout", destroy_user_session_path, :method => :delete
    end
  end

end

app/helpers/leaderboards_helper.rb
module LeaderboardsHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/predictions_helper.rb
module PredictionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/Fixtures/index.html.erb
<h1>Fixtures</h1>

<% @fixtures.each do |fixture| %>
  <li><%= fixture.team_a_name %> : <%= fixture.team_b_name %> date: <%= fixture.match_date%></li>
<% end %>

app/views/Fixtures/new.html.erb
<%= form_for @fixture do |f| %>
<%= f.label :team_a_name, "Team A" %><%= f.text_field :team_a_name %><br/>
<%= f.label :team_b_name, "Team B" %><%= f.text_field :team_b_name %><br/>
<%= f.label :match_date %><%= f.date_select :match_date %><br/>
<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PLPredictions</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <ul class="nav">
        <li class="active"><a href="/">Home</a></li>
        <li><%= link_to "Points Criteria", points_path %></a></li>
        <li><%= link_to "All Predictions", predictions_path %></a></li>
        <li><%= link_to "Make My Predictions", new_prediction_path %></a></li>
        <li><%= link_to "View My Predictions", my_predictions_path %></a></li>
        <li><%= link_to "Leaderboard", leaderboard_path %></li>
        <li><%= link_to "Fixtures", fixtures_path %></li>
        <li><%= link_to "Results", results_path %></a></li>
        <li><%= display_login %></li> 
    </div>
  </div>
</div>

<%= yield %>

</body>
</html>

app/views/leaderboards/index.html.erb
<h1>LeaderBoard</h1>
<h2>Current table below</h2>

<p>Tom - 110</p>
<p>Nav - 102</p>
<p>Browny and Sam R - 98</p>
<p>Daz and Sam K - 95</p>
<p>Lickers - 84</p>
<p>Alex - 75</p>
<p>Joe - 68</p>

app/views/points/index.html.erb
<h1>Points criteria as follows:</h1>
<p>Three points for a correct score.</p>
<p>One point for a right result - Example: If you predict Man City 2-1 Man Utd, but the final result is Man City 3-1 Man Utd, this earns you one point.</p> 

app/views/predictions/index.html.erb
<h1>Make Your Predictions</h1>

<% @predictions.each do |prediction| %>
  <li><%= prediction.team_a_name %> <%= prediction.team_a_score %>: <%= prediction.team_b_name %> <%= prediction.team_b_score %>date: <%= prediction.match_date%></li>
<% end %>

app/views/predictions/my_predictions.html.erb
<% @predictions.each do |prediction| %>
  <li><%= prediction.team_a_name %> <%= prediction.team_a_score %>: <%= prediction.team_b_name %> <%= prediction.team_b_score %>date: <%= prediction.match_date%></li>
<% end %>

app/views/predictions/new.html.erb
<%= form_for @prediction do |f| %>
  <% @fixtures.each do |fixture| %>
    <h1><%= fixture.match_date %></h1>
  <!-- team a stuff -->
    <%= fixture.team_a_name %>
    <%= hidden_field_tag "predictions[][team_a_name]", fixture.team_a_name %><br/>
    <%= text_field_tag "predictions[][team_a_score]", nil %><br/>
    <!-- team b stuff -->
    <%= fixture.team_b_name %>
    <%= hidden_field_tag "predictions[][team_b_name]", fixture.team_b_name %><br/>
    <%= text_field_tag "predictions[][team_b_score]", nil %><br/>

    <%= hidden_field_tag "predictions[][match_date]", fixture.match_date %><br/>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/results/index.html.erb
<h1>Results - Previous 3 Matchdays</h1>
<h2>24th-25th November</h2>
<p>Sunderland 2-4 West Brom</p>
<p>Everton 1-1 Norwich</p>
<p>Man Utd 3-1 QPR</P>
<P>Stoke 1-0 Fulham</p>
<p>Wigan 3-2 Reading</p>
<p>Aston Villa 0-0 Arsenal</p>
<p>Swansea 0-0 Liverpool</p>
<p>Southampton 2-0 Newcastle</p>
<p>Chelsea 0-0 Man City</p>
<p>Tottenham 3-1 West Ham</p>